import type { ByteSource } from './byte-source.js';
import type { CancelSignal } from '../cancel.js';

/**
 * Append-only destination for generated bytes (the optimized archive).
 * Adapters write to a temporary file (CLI) or collect Blob parts (web).
 */
export interface ByteSink {
  /** Appends bytes. */
  write(chunk: Uint8Array): Promise<void>;
  /**
   * Optionally appends [start, end) of a source without copying through
   * JavaScript buffers (e.g. Blob slices in the browser). When absent the
   * writer streams the range through `write`.
   */
  writeRange?(source: ByteSource, start: number, end: number, signal?: CancelSignal): Promise<void>;
  /** Number of bytes written so far. */
  readonly bytesWritten: number;
}

/** In-memory sink used by tests and for small archives. */
export class MemoryByteSink implements ByteSink {
  private readonly parts: Uint8Array[] = [];
  bytesWritten = 0;

  /** Stores a copy of the chunk. */
  write(chunk: Uint8Array): Promise<void> {
    this.parts.push(chunk.slice());
    this.bytesWritten += chunk.length;
    return Promise.resolve();
  }

  /** Returns the concatenated bytes written so far. */
  toBytes(): Uint8Array {
    const out = new Uint8Array(this.bytesWritten);
    let offset = 0;
    for (const p of this.parts) {
      out.set(p, offset);
      offset += p.length;
    }
    return out;
  }
}
